Repository cert-manager/istio-csr, pull requests merged in 2021-05, with the labels that each got.

#51 Allow the TrustDomain to be set.
  cmd/app/options/options.go
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  hack/demo/values.yaml
  hack/istio-config-1.7.6.yaml
  hack/istio-config-1.8.2.yaml
  hack/istio-config-1.9.1.yaml
  test/e2e/suite/request/request.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#54 Sets USER to 1001 in Dockerfile
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#58 Updates for tag release v0.1.3
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
  hack/demo/deploy-demo.sh
  hack/demo/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
