Repository cert-manager/istio-csr, pull requests merged in 2021-03, with the labels that each got.

#34 Adds istio v1.9 to tests, and make it the default
  Makefile
  README.md
  hack/istio-config-1.9.1.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#35 Updates manifests for release v0.1.1
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
  hack/demo/deploy-demo.sh
  hack/demo/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#38 Add myself to the OWNERS file
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#37 Intoduce more in-depth CSR extension validation
  pkg/server/auth.go
  pkg/server/auth_test.go
  pkg/server/internal/extensions/extensions.go
  pkg/server/internal/extensions/extensions_test.go
  test/gen/csr.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#40 Adds wait to namespace controller propagation test
  test/e2e/suite/namespace/namespace.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#39 Updates tags to v0.1.2
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
  hack/demo/deploy-demo.sh
  hack/demo/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
