Repository cert-manager/istio-csr, pull requests merged in 2021-06, with the labels that each got.

#59 Adds istio v1.10.0 version target and make default e2e test
  Makefile
  README.md
  go.mod
  go.sum
  hack/istio-config-1.10.0.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#60 Added the ability to set dns names in the istio-csr certificate.
  cmd/app/options/options.go
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  hack/demo/values.yaml
  pkg/tls/tls.go
  test/e2e/suite/internal/client/client.go
  test/e2e/suite/request/request.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/M

#62 Exit error if we lose leader election, fix election ID
  cmd/app/app.go
  pkg/controller/namespace.go
  pkg/tls/tls.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#68 Remove test boilerplate files
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
Labels: approved, dco-signoff: yes, lgtm, size/M

#67 Update Deps
  cmd/app/options/options.go
  go.mod
  go.sum
  hack/demo/deploy-demo.sh
  pkg/server/auth_test.go
  pkg/server/server.go
  test/e2e/suite/internal/client/client.go
  test/e2e/suite/request/request.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#69 Create new cert-manager package
  cmd/app/app.go
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/_helpers.tpl
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/configmap.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/templates/rolebinding.yaml
  deploy/charts/istio-csr/templates/service.yaml
  deploy/charts/istio-csr/values.yaml
  hack/demo/deploy-demo.sh
  hack/demo/istio-csr-values.yaml
  hack/demo/values.yaml
  pkg/certmanager/certmanager.go
  pkg/controller/namespace.go
  pkg/server/auth.go
  pkg/server/auth_test.go
  pkg/server/server.go
  pkg/tls/tls.go
  pkg/util/healthz.go
  pkg/util/healthz_test.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#70 Change istio config to use "append last" in patches
  hack/istio-config-1.10.0.yaml
  hack/istio-config-1.7.6.yaml
  hack/istio-config-1.8.2.yaml
  hack/istio-config-1.9.1.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#71 Make all istio-csr internal services into controller-runtime runnables.
  cmd/app/app.go
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  pkg/certmanager/certmanager.go
  pkg/controller/namespace.go
  pkg/controller/namespace_test.go
  pkg/server/auth.go
  pkg/server/auth_test.go
  pkg/server/server.go
  pkg/tls/tls.go
  pkg/util/healthz.go
  pkg/util/healthz_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#63 Change default certificate settings
  README.md
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#72 Add metrics
  cmd/app/app.go
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/metrics-service.yaml
  deploy/charts/istio-csr/templates/metrics-servicemonitor.yaml
  deploy/charts/istio-csr/values.yaml
  go.mod
  go.sum
  pkg/server/server.go
  pkg/tls/tls.go
  test/e2e/suite/request/request.go
Labels: approved, dco-signoff: yes, lgtm, size/L
