Repository cert-manager/istio-csr, pull requests merged in 2021-07, with the labels that each got.

#77 Bumps base image version
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#76 Fix custom volume and volumeMount helm template
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#74 Change delete CertificateRequest to defer so it is always done
  go.mod
  pkg/certmanager/certmanager.go
  pkg/certmanager/certmanager_test.go
  pkg/certmanager/fake/fake.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/tls/tls.go
  test/gen/certificaterequest.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#75 Server unit tests
  pkg/certmanager/certmanager.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/tls/tls.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#78 Pass context to tls.GetConfig so it returns when context is canceled
  pkg/server/server.go
  pkg/tls/tls.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#79 Updates image tags to v0.2.0
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
  hack/demo/deploy-demo.sh
  hack/demo/istio-csr-values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#82 Adds .app.tls.istiodCertificateDuration helm field as value to istiod's certificate.spec.,duration
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
