Repository cert-manager/istio-csr, pull requests merged in 2022-06, with the labels that each got.

#154 Make cert install controllable in helm
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#158 upgrade istio, cert-manager, helm
  Makefile
  hack/demo/deploy-demo.sh
  hack/istio-config-1.13.4.yaml
  test/carotation/env.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#160 Removes docs from repo in favour of using cert-manager.io
  README.md
  docs/example-cluster-issuer.yaml
  docs/example-issuer.yaml
  docs/getting_started.md
  docs/istio-config-getting-started.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved
