Repository cert-manager/istio-csr, pull requests merged in 2022-07, with the labels that each got.

#163 Create `go.mod` in `hack/tools`
  Makefile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tool.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#167 Increase bits to 4096 for more security
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  pkg/tls/tls.go
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#171 Increase the kubectl wait timeout for the e2e test carotation setup scripts
  test/carotation/setup-2.sh
  test/carotation/test-2.sh
Labels: dco-signoff: yes, lgtm, approved, size/S

#164 Updates go modules versions
  go.mod
  go.sum
  pkg/certmanager/certmanager.go
  pkg/certmanager/certmanager_test.go
  pkg/certmanager/fake/fake.go
  pkg/server/internal/extensions/extensions_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/tls/rootca/rootca.go
  pkg/tls/rootca/rootca_test.go
  pkg/tls/tls.go
  test/e2e/framework/config/config.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/helper.go
  test/e2e/suite/namespace/namespace.go
  test/e2e/suite/request/request.go
  test/gen/certificaterequest.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#169 Remove istio config manifests in /hack for istio versions v1.7 to v1.9
  hack/istio-config-1.7.6.yaml
  hack/istio-config-1.8.2.yaml
  hack/istio-config-1.9.1.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#157 Allows image pull secret parameter setting in helm chart
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/serviceaccount.yaml
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#173 Updates version to v0.5.0
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#174 Update README.md to state that istio-csr only now supports istio v1.10+
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS
