Repository cert-manager/istio-csr, pull requests merged in 2023-05, with the labels that each got.

#179 Allow ECDSA serving certificate
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  pkg/tls/tls.go
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#194 Add IstioOperator CR for v1.17.0
  Makefile
  hack/istio-config-1.17.2.yaml
  test/carotation/env.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#209 Update istio libs
  go.mod
  go.sum
  pkg/server/server.go
  test/e2e/suite/internal/client/client.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#206 Add namespace values in Helm template
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/metrics-service.yaml
  deploy/charts/istio-csr/templates/metrics-servicemonitor.yaml
  deploy/charts/istio-csr/templates/service.yaml
  deploy/charts/istio-csr/templates/serviceaccount.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS
