Repository cert-manager/istio-csr, pull requests merged in 2023-02, with the labels that each got.

#114 A service isn't a requirement for the servicemonitor
  deploy/charts/istio-csr/templates/metrics-servicemonitor.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#190 Update go to 1.19, update dependencies
  Dockerfile
  Makefile
  go.mod
  go.sum
  hack/istio-config-1.13.1.yaml
  hack/istio-config-1.13.4.yaml
  hack/istio-config-1.14.1.yaml
  hack/istio-config-1.14.6.yaml
  hack/istio-config-1.15.5.yaml
  hack/istio-config-1.16.2.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/server/auth.go
  pkg/server/auth_test.go
  test/carotation/env.sh
  test/e2e/suite/internal/client/client.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved, ok-to-test

#188 Remove controller.rootCAConfigMapName from helm values
  hack/demo/istio-csr-values.yaml
  test/carotation/values/istio-csr-1.yaml
  test/carotation/values/istio-csr-2.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#185 Add support for setting namespace for istio control plane. Fixes #152
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#193 Update OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: dco-signoff: yes, lgtm, approved, size/S

#195 Limit namespaces for configmaps, useful for multitenant environments
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test
