Repository cert-manager/istio-csr, pull requests merged in 2023-03, with the labels that each got.

#196 Seperate Role permissions between leases for leader election and cert…
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/templates/role_leases.yaml
  deploy/charts/istio-csr/templates/rolebinding_leases.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#201 Release v0.6.0-alpha.0
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test

#203 Release v0.6.0
  Makefile
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S
