Repository cert-manager/istio-csr, pull requests merged in 2024-10, with the labels that each got.

#424 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#425 fix(helm): quote `istiodAdditionalDNSNames` to support wildcard domains
  deploy/charts/istio-csr/templates/certificate.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#429 Use a default (but configurable) test file for istio-csr
  make/config/istio/istio-config-1.17.8.yaml
  make/config/istio/istio-config-1.18.7.yaml
  make/config/istio/istio-config-1.19.6.yaml
  make/config/istio/istio-config-1.19.9.yaml
  make/config/istio/istio-config-1.20.2.yaml
  make/config/istio/istio-config-1.20.8.yaml
  make/config/istio/istio-config-1.21.4.yaml
  make/config/istio/istio-config-1.22.2.yaml
  make/config/istio/istio-config-1.22.3.yaml
  make/config/istio/istio-config-1.23.0.yaml
  make/config/istio/istio-config-default.yaml
  make/test-e2e.mk
Labels: dco-signoff: yes, size/L, lgtm, approved

#422 fix: expose ALPN in TLS handshake
  pkg/tls/tls.go
Labels: dco-signoff: yes, lgtm, approved, size/XS, ok-to-test

#430 Various e2e setup tweaks
  make/test-e2e.mk
Labels: dco-signoff: yes, lgtm, approved, size/XS
