Repository cert-manager/istio-csr, pull requests merged in 2024-01, with the labels that each got.

#225 Upgrade ginkgo to v2
  Makefile
  go.mod
  go.sum
  hack/run-e2e.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tool.go
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/framework.go
  test/e2e/suite/mtls/mtls.go
  test/e2e/suite/namespace/namespace.go
  test/e2e/suite/request/request.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#226 Use upstream images instead of custom built images
  test/carotation/workloads/sleep.yaml
  test/e2e/manifests/httpbin.yaml
  test/e2e/manifests/sleep.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XS

#229 Upload junit and coverage results to ARTIFACTS folder
  make/test-e2e.mk
  make/test-unit.mk
Labels: dco-signoff: yes, lgtm, approved, size/S

#237 Upgrade repository-base module
  .github/workflows/make-self-upgrade.yaml
  Makefile
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
Labels: dco-signoff: yes, lgtm, approved, size/XS

#241 Add spectralhiss as reviewer for istio-csr
  OWNERS
Labels: dco-signoff: yes, lgtm, approved, size/XS

#245 Upgrade oci-image module
  klone.yaml
  make/00_mod.mk
  make/_shared/oci-image/01_mod.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#247 Set controller-runtime global logger
  cmd/app/app.go
Labels: dco-signoff: yes, lgtm, approved, size/XS

#230 Preload images used in e2e tests
  make/00_mod.mk
  make/test-carotation.mk
  test/carotation/cleanup-1.sh
  test/carotation/env.sh
  test/carotation/run.sh
  test/carotation/setup-1.sh
  test/carotation/setup-2.sh
  test/carotation/setup-3.sh
  test/carotation/test-1.sh
  test/carotation/test-2.sh
  test/carotation/workloads/httpbin.yaml
  test/carotation/workloads/sleep.yaml
  test/e2e/manifests/httpbin.yaml
  test/e2e/manifests/sleep.yaml
Labels: dco-signoff: yes, size/L, lgtm, approved

#252 Use standardised release process
  make/02_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/XS

#253 Fix typo which defines unused variable
  make/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/XS

#255 Cleanup chart properties
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
Labels: dco-signoff: yes, lgtm, approved, size/XS

#254 Use Helm template to generate image OCI path
  deploy/charts/istio-csr/Chart.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/_helpers.tpl
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#256 Use helm tool
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
  make/00_mod.mk
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#262 add ability to provide additional DNS names to istiod certificate
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/values.yaml
  test/carotation/values/istio-csr-2.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, ok-to-test
