Repository cert-manager/istio-csr, pull requests merged in 2024-08, with the labels that each got.

#364 Add retries for issuing initial serving cert
  go.mod
  pkg/certmanager/certmanager.go
  pkg/tls/tls.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#366 Add some release detail which appears to be missing
  RELEASE.md
Labels: dco-signoff: yes, lgtm, approved, size/XS

#369 Add security context to istio-csr deployment
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#370 Add end to end test for client certificate authenticator
  make/test-e2e.mk
  test/e2e/suite/internal/client/client.go
  test/e2e/suite/request/request.go
  test/gen/csr.go
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#387 Add Istio 1.23 tests
  make/config/istio/istio-config-1.23.0.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S, needs-ok-to-test

#389 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#336 Add support for impersonation for certificate requests
  README.md
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/clusterrole.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  go.mod
  go.sum
  make/config/istio/istio-config-1.22.3.yaml
  make/test-e2e.mk
  pkg/server/auth.go
  pkg/server/auth_test.go
  pkg/server/node_auth.go
  pkg/server/node_auth_test.go
  pkg/server/server.go
  pkg/server/server_test.go
  test/e2e/framework/config/config.go
  test/e2e/suite/mtls/mtls.go
  test/e2e/suite/runtimeconfiguration/runtimeconfiguration.go
  test/ecc/reset-istio-csr.sh
Labels: dco-signoff: yes, size/XXL, lgtm, approved, ok-to-test
