Repository cert-manager/istio-csr, pull requests merged in 2024-02, with the labels that each got.

#267 Remove README header since it is already included in the artifacthub sidebar
  deploy/charts/istio-csr/README.md
Labels: dco-signoff: yes, lgtm, approved, size/S

#268 Fix values.yaml
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#273 Add 'crds.enabled' and 'crds.keep' options to generated CRDs
  klone.yaml
  make/00_mod.mk
  make/_shared/helm/crd.template.footer.yaml
  make/_shared/helm/crd.template.header.yaml
  make/_shared/helm/crds.mk
  make/_shared/helm/helm.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#258 Enable helm-tool linter and schema generator
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.linter.exceptions
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  make/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/XL

#280 Helm Uniformize label options
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/_helpers.tpl
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/clusterrole.yaml
  deploy/charts/istio-csr/templates/clusterrolebinding.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/metrics-service.yaml
  deploy/charts/istio-csr/templates/metrics-servicemonitor.yaml
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/templates/role_leases.yaml
  deploy/charts/istio-csr/templates/rolebinding.yaml
  deploy/charts/istio-csr/templates/rolebinding_leases.yaml
  deploy/charts/istio-csr/templates/service.yaml
  deploy/charts/istio-csr/templates/serviceaccount.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#274 Hef/csr p384 generation fix
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  make/02_mod.mk
  make/test-ecc.mk
  pkg/tls/tls.go
  test/ecc/.gitignore
  test/ecc/cleanup.sh
  test/ecc/env.sh
  test/ecc/issuers/root.yaml
  test/ecc/issuers/selfsigned.yaml
  test/ecc/reset-istio-csr.sh
  test/ecc/run.sh
  test/ecc/setup.sh
  test/ecc/test.sh
  test/ecc/values/istio-csr-ecdsa_p256.yaml
  test/ecc/values/istio-csr-ecdsa_p384.yaml
  test/ecc/values/istio-ecdsa_p256.yaml
  test/ecc/values/istio-ecdsa_p384.yaml
  test/ecc/workloads/httpbin.yaml
  test/ecc/workloads/sleep.yaml
Labels: dco-signoff: yes, lgtm, approved, size/XL
