Repository cert-manager/istio-csr, pull requests merged in 2024-09, with the labels that each got.

#396 Propagate annotations
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.yaml
  make/config/istio-csr-pure-runtime-values.yaml
  pkg/istiodcert/options.go
  pkg/istiodcert/worker.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#398 Tweak roles to fix permission errors
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/templates/role_dynamic_istiod.yaml
  deploy/charts/istio-csr/templates/role_leases.yaml
  deploy/charts/istio-csr/templates/rolebinding_dynamic_istiod.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#372 added labels and annotations to deployment and pod
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test
