Repository cert-manager/istio-csr, pull requests merged in 2024-07, with the labels that each got.

#341 Add option to focus a specific e2e test
  make/test-e2e.mk
Labels: dco-signoff: yes, lgtm, approved, size/XS

#343 Add ability to configure issuer at runtime
  cmd/app/app.go
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  make/config/istio-csr-values.yaml
  make/test-e2e.mk
  pkg/certmanager/certmanager.go
  pkg/certmanager/certmanager_test.go
  test/e2e/framework/config/config.go
  test/e2e/framework/helper/helper.go
  test/e2e/runtimeconfig-manifests/configmap/configmap.yaml
  test/e2e/runtimeconfig-manifests/issuers/issuer.yaml
  test/e2e/suite/doc.go
  test/e2e/suite/mtls/mtls.go
  test/e2e/suite/runtimeconfiguration/runtimeconfiguration.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#344 Bump dep for CVE-2024-28122, ignore false positive istio vulns
  .trivyignore
  go.mod
  go.sum
Labels: dco-signoff: yes, lgtm, approved, size/S

#345 Add updated versions of istio config to enable tests
  make/config/istio/istio-config-1.19.9.yaml
  make/config/istio/istio-config-1.20.8.yaml
  make/config/istio/istio-config-1.21.4.yaml
  make/config/istio/istio-config-1.22.2.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#348 Increase timeout for namespace e2e test polling
  make/test-e2e.mk
  test/e2e/suite/namespace/namespace.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#349 Add nameOverride to values.yaml so it is allowed by the jsonSchema validation
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/values.linter.exceptions
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/S

#353 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/oci-build/image_tool/go.mod
  make/_shared/oci-build/image_tool/go.sum
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#355 Helm updates for istiod cert
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M

#354 add flag to set log-format
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#358 Configure istio logging when JSON selected
  cmd/app/options/options.go
Labels: dco-signoff: yes, lgtm, approved, size/S

#352 Disable kubernetes client side rate limiting
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  make/test-e2e.mk
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test

#359 Add ability to dynamically configure istiod cert
  cmd/app/app.go
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/certificate.yaml
  deploy/charts/istio-csr/templates/clusterrole.yaml
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/templates/role.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  make/config/istio-csr-pure-runtime-values.yaml
  make/test-e2e.mk
  pkg/certmanager/certmanager.go
  pkg/istiodcert/options.go
  pkg/istiodcert/worker.go
  pkg/tls/tls.go
  test/e2e-pure-runtime/e2e_test.go
  test/e2e-pure-runtime/initial-manifests/README.md
  test/e2e-pure-runtime/initial-manifests/configmap.yaml
  test/e2e-pure-runtime/manifests/issuer.yaml
  test/e2e-pure-runtime/manifests/sleep.yaml
  test/e2e-pure-runtime/suite/suite.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#357 Implement client cert auth
  cmd/app/options/options.go
  deploy/charts/istio-csr/README.md
  deploy/charts/istio-csr/templates/deployment.yaml
  deploy/charts/istio-csr/values.schema.json
  deploy/charts/istio-csr/values.yaml
  go.mod
  go.sum
  pkg/server/auth.go
  pkg/server/auth_test.go
  pkg/server/server.go
  pkg/server/server_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved, ok-to-test
